os:
  - linux
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

language: java
sudo: false
script: mvn clean verify
notifications:
  slack: 'epam-krk-ja-2016:ue1xfXTh5tCq9yeey4qPILna#expansion-team'
